[alembic]
script_location = alembic
sqlalchemy.url = driver://user:pass@localhost/dbname  # will be overridden by env.py
post_write_hooks = 
hooks = black
black.type = console_scripts
black.entrypoint = black
black.options = -l 88 REVISION_SCRIPT_FILENAME